import { SimpleGit } from "simple-git";
import path from "path";
import fs from "fs";
import { FileRecord } from "../pipeline.types"
import crypto from "crypto";

const CODE_EXTS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".py", ".java", ".kt",
    ".go", ".rs", ".rb", ".php", ".cs", ".swift", ".c", ".cpp", ".scala"]);

const KEEP_NONCODE = new Set([".html", ".css", ".scss", ".sql", ".graphql", ".prisma",
    ".yml", ".yaml", ".json", ".toml", ".md", ".proto", ".tf"]);

const EXCLUDE_DIRS = new Set(["node_modules", "vendor", "dist", "build", "target", ".next",
    "__pycache__", ".venv", "coverage", ".git", "bin", "obj", ".vscode", ".cursor", ".antigravity", ".claude"]);

const EXCLUDE_FILES = new Set(["package-lock.json", "yarn.lock", "pnpm-lock.yaml",
    "poetry.lock", "go.sum", "Cargo.lock", "composer.lock", ".gitignore", ".dockerignore"]);

// Intent files feed the L4 bundle (project purpose, stack, deployment).
// Everything else non-code rides along into its folder's module instead —
// an HTML template or SQL migration belongs next to the code that uses it,
// not in the 32K-char intent bundle where it would crowd out the README.
const INTENT_RES: RegExp[] = [
    /(^|\/)readme[^/]*$/i,
    /^docs\/.+\.md$/i,
    /(^|\/)(package\.json|pyproject\.toml|pom\.xml|build\.gradle[^/]*|go\.mod|requirements\.txt|composer\.json|gemfile)$/i,
    /(^|\/)(dockerfile|docker-compose[^/]*\.ya?ml)$/i,
    /^\.github\/workflows\/[^/]+\.ya?ml$/i,
    /(^|\/)\.env\.example$/i,
];

const isIntentFile = (rel: string): boolean => {

    for (const re of INTENT_RES) {

        if (re.test(rel)) {
            return true;
        }
    }

    return false;
};

export const getRepoFiles = async (git: SimpleGit, repoPath: string) => {
    const git_ls = await git.raw(["ls-files"]);
    const files: string[] = git_ls
        .trim()
        .split('\n')
        .filter(Boolean);   // empty repo -> [""] without this guard

    const codeFiles: FileRecord[] = [];
    const intentFiles: FileRecord[] = [];
    const others: FileRecord[] = [];

    for (const rel of files) {
        const ext = path.extname(rel).toLowerCase();
        if (rel.split("/").some(p => EXCLUDE_DIRS.has(p))) 
            continue;

        if (EXCLUDE_FILES.has(path.basename(rel)))
            continue;

        // Classify by extension BEFORE reading — skips disk I/O for files we
        // would drop anyway (images, model weights, unknown extensions).
        const relevant = CODE_EXTS.has(ext) || KEEP_NONCODE.has(ext) || isIntentFile(rel);

        if (!relevant)
            continue;

        // git ls-files can list files that are tracked but absent from the
        // working tree (deleted locally, sparse checkout, broken symlink).
        // One unreadable file must never kill the run.
        let buf: Buffer;

        try {
            buf = await fs.promises.readFile(path.join(repoPath, rel));
        } catch {
            continue;
        }

        if (buf.length > 1_000_000 || buf.includes(0))
            continue;         // huge or binary
        
        const head = buf.subarray(0, 400).toString("utf8");
        
        if (/@generated|DO NOT EDIT|Code generated by/.test(head)) 
            continue;

        const record: FileRecord = {
            path: rel,
            ext,
            sizeBytes: buf.length,
            isCode: CODE_EXTS.has(ext),
            contentHash: crypto.createHash("sha256").update(buf).digest("hex"),
        };

        if (isIntentFile(rel)) {
            intentFiles.push(record);
        }
        else if (CODE_EXTS.has(ext)) {
            codeFiles.push(record);
        }
        else if (KEEP_NONCODE.has(ext)) {
            others.push(record);          // rides along into its folder's module
        }
        // unknown extensions: dropped (binaries already excluded above)
    }

    return { git_ls, codeFiles, intentFiles, others };
}
