import { SimpleGit, simpleGit } from "simple-git";
import path from "path";
import fs from "fs";
import { FileRecord } from "../pipeline.types"
import crypto from "crypto";

const CODE_EXTS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".py", ".java", ".kt",
    ".go", ".rs", ".rb", ".php", ".cs", ".swift", ".c", ".cpp", ".scala"]);

const KEEP_NONCODE = new Set([".html", ".css", ".scss", ".sql", ".graphql", ".prisma",
    ".yml", ".yaml", ".json", ".toml", ".md", ".proto", ".tf"]);

const EXCLUDE_DIRS = new Set(["node_modules", "vendor", "dist", "build", "target", ".next",
    "__pycache__", ".venv", "coverage", ".git", "bin", "obj", ".vscode", ".cursor", ".antigravity", ".claude"]);

const EXCLUDE_FILES = new Set(["package-lock.json", "yarn.lock", "pnpm-lock.yaml",
    "poetry.lock", "go.sum", "Cargo.lock", "composer.lock", ".gitignore", ".dockerignore"]);

const INTENT_FILES = new Set(["Dockerfile"]);

export const getRepoFiles = async (git: SimpleGit, repoPath: string) => {
    const git_ls = await git.raw(["ls-files"]);
    const files: string[] = git_ls
        .trim()
        .split('\n');

    const codeFiles: FileRecord[] = [];
    const intentFiles: FileRecord[] = [];
    const others: FileRecord[] = [];

    for (const rel of files) {
        const ext = path.extname(rel).toLowerCase();
        if (rel.split("/").some(p => EXCLUDE_DIRS.has(p))) 
            continue;

        if (EXCLUDE_FILES.has(path.basename(rel))) 
            continue;
        
        const buf = await fs.promises.readFile(path.join(repoPath, rel));
        
        if (buf.length > 1_000_000 || buf.includes(0)) 
            continue;         // huge or binary
        
        const head = buf.subarray(0, 400).toString("utf8");
        
        if (/@generated|DO NOT EDIT|Code generated by/.test(head)) 
            continue;

        if (KEEP_NONCODE.has(ext) || INTENT_FILES.has(path.basename(rel))) {
            intentFiles.push({
                path: rel,
                ext,
                sizeBytes: buf.length,
                isCode: false,
                contentHash: crypto.createHash("sha256").update(buf).digest("hex"),
            });
        }
        else if(CODE_EXTS.has(ext)){
            codeFiles.push({
                path: rel, ext, sizeBytes: buf.length, isCode: CODE_EXTS.has(ext),
                contentHash: crypto.createHash("sha256").update(buf).digest("hex"),
            });
        }
        else{
            others.push({
                path: rel, 
                ext, 
                sizeBytes: buf.length, 
                isCode: CODE_EXTS.has(ext),
                contentHash: crypto.createHash("sha256").update(buf).digest("hex"),
            });
        }
        
    }

    return { git_ls, codeFiles, intentFiles, others };
}
const main = () => {
    const p = async () => {
        const git = simpleGit()
        await getRepoFiles(git, "C:/Coding/projects/autoDocs/server"
        );
    }
    p();
}
main()
