import fs from "node:fs";
import nodePath from "node:path";
import simpleGit, { SimpleGit } from "simple-git";

import prisma from "../prisma/prisma";
import { generate, llmConcurrency } from "../LLM/index";

import {
    FileRecord, IntentBundle, Module, ModuleDocResult, ValidationFinding, IncompleteFeature,
    TinyDocResult, ArchDocResult, CustomInstructions,
} from "./pipeline.types";
import {
    mapWithConcurrency, buildFileTree, guessEntryPoints, buildDocFileNames,
} from "./pipeline.helper";
import { loadCustomInstructions } from "./pipeline.customInstructions";

import { getRepoFiles } from "./stages/L1.inventory";
import { groupModules, buildFileToModuleIndex } from "./stages/L2.prefixCompressor";
import { buildModuleEdges } from "./stages/L3.dynamicGrouper";
import { buildIntentBundle } from "./stages/L4.intentBundle";
import { isTinyRepo, computeStaleness } from "./stages/L5.router";
import {
    buildModulePrompt, buildArchPrompt, buildValidationPrompt, buildTinyPrompt,
    buildOwnerReport,
} from "./stages/L6.promptBuilder";
import { MODULE_DOC_SCHEMA, VALIDATION_SCHEMA, TINY_DOC_SCHEMA, ARCH_DOC_SCHEMA } from "./stages/L6.prompts";
import { applyValidationFindings } from "./stages/L6.applyEdits";

// ============================================================================
// The worker-facing result: how many md files were produced, plus the content.
// ============================================================================

export interface DocGenResult {
    route: "TINY" | "NORMAL";
    moduleDocCount: number;
    moduleDocs: Record<string, string>;    // "auth.md" -> markdown (ready to write to disk)
    fileIndex: Record<string, string>;     // "auth.md" -> module id (trace back to DB rows)
    archDoc: string;                       // always exactly one arch doc
    archDocFileName: string;               // "ARCHITECTURE.md"
    ownerReport: string | null;            // second output: message to the repo owner

    // Non-fatal problems worth telling the user about. The worker copies these
    // into the run's notification row.
    warnings: string[];

    // PR metadata for committing the docs — generated by the final LLM call
    // (arch call on NORMAL, tiny call on TINY) as SEPARATE structured fields,
    // so none of it can appear inside the doc markdown above.
    commitMessage: string;
    prTitle: string;
    prBody: string;
    stats: {
        modulesTotal: number;
        modulesRegenerated: number;
        modulesFromCache: number;
        modulesDeleted: number;
        resolutionRate: number | null;
        promptVersion: string;
    };
}

// ============================================================================
// generateFirstTimeDocs — the full first-import pipeline, L1 -> L6.
//
// This is ALSO safe to re-run at any time: staleness is computed against
// module_docs rows, so an interrupted import resumes where it stopped, and a
// second invocation on an unchanged repo skips every module call (see L5).
// ============================================================================

export const generateFirstTimeDocs = async (
    repoId: string,
    repoPath: string,
): Promise<DocGenResult> => {

    const warnings: string[] = [];

    // ---- L0: the owner's custom instructions -------------------------------
    // effectiveVersion folds the instructions into the staleness key, so editing
    // them regenerates the docs they influenced.
    const { custom, effectiveVersion } = await loadCustomInstructions(repoId, warnings);

    // ---- L0/L1: inventory --------------------------------------------------
    const git = simpleGit(repoPath);

    const { codeFiles, intentFiles, others } = await getRepoFiles(git, repoPath);

    // Cached reader: L3 reads every code file, L6 reads many again — one disk
    // hit per file. Repo-relative path in, source text out.
    const cache = new Map<string, string>();

    const readFile = (relPath: string): string => {

        if (!cache.has(relPath)) {
            cache.set(relPath, fs.readFileSync(nodePath.join(repoPath, relPath), "utf8"));
        }

        return cache.get(relPath)!;
    };

    // ---- L4: intent bundle (needed on BOTH routes) ---------------------------
    const intent = buildIntentBundle(intentFiles, readFile);

    // ---- L5a: size decision — before any grouping/graph work ------------------
    if (isTinyRepo([...codeFiles, ...others])) {
        const tinyResult = await runTinyPath(repoId, codeFiles, others, intent, readFile, custom, effectiveVersion, warnings);
        await persistDocsPointer(repoId, git, warnings);
        return tinyResult;
    }

    // ---- L2/L3: deterministic layer -------------------------------------------
    const modules: Module[] = groupModules(codeFiles, others, { promptVersion: effectiveVersion });
    const fileToModule = buildFileToModuleIndex(modules);

    const { edges, resolutionRate, fileImportCounts } =
        buildModuleEdges(codeFiles, readFile, fileToModule);

    // ---- L5b: staleness — empty table on a true first run => all stale --------
    const storedRows = await prisma.moduleDoc.findMany({
        where: { repo_id: repoId },
        select: { module_id: true, input_hash: true },
    });

    const storedHashes = new Map(storedRows.map(r => [r.module_id, r.input_hash]));

    const { staleModules, cachedModuleIds, deletedModuleIds } =
        computeStaleness(modules, storedHashes);

    // ---- L6a: module docs (fan-out, cache-warm-first, per-call persist) -------
    const moduleDocs = new Map<string, string>();
    const incompleteByModule = new Map<string, IncompleteFeature[]>();

    const generateOne = async (module: Module): Promise<void> => {

        const prompt = buildModulePrompt(module, readFile, edges, intent, fileImportCounts, custom.module);

        const { data } = await generate<ModuleDocResult>("moduleDoc", prompt, MODULE_DOC_SCHEMA);

        moduleDocs.set(module.id, data.markdown);
        incompleteByModule.set(module.id, data.incomplete);

        // Persist IMMEDIATELY, not at the end of the run: if the process dies
        // at module 31/40, the next invocation finds 31 matching hashes and
        // only pays for the remaining 9. This upsert IS the crash-resume.
        await prisma.moduleDoc.upsert({
            where: { repo_id_module_id: { repo_id: repoId, module_id: module.id } },
            create: {
                repo_id: repoId,
                module_id: module.id,
                display_name: module.displayName,
                input_hash: module.inputHash,
                markdown: data.markdown,
                incomplete: JSON.parse(JSON.stringify(data.incomplete)),
            },
            update: {
                display_name: module.displayName,
                input_hash: module.inputHash,
                markdown: data.markdown,
                incomplete: JSON.parse(JSON.stringify(data.incomplete)),
            },
        });
    };

    if (staleModules.length > 0) {

        // First call alone: it WRITES the shared prompt-prefix cache;
        // the concurrent rest then READ it at ~10% input price.
        await generateOne(staleModules[0]);

        await mapWithConcurrency(staleModules.slice(1), llmConcurrency(), generateOne);
    }

    // Cached modules (crash-resume / re-run): load stored docs so validation
    // and the arch call always see the COMPLETE doc set.
    if (cachedModuleIds.length > 0) {

        const cachedRows = await prisma.moduleDoc.findMany({
            where: { repo_id: repoId, module_id: { in: cachedModuleIds } },
        });

        for (const row of cachedRows) {
            moduleDocs.set(row.module_id, row.markdown);
            incompleteByModule.set(row.module_id, row.incomplete as unknown as IncompleteFeature[]);
        }
    }

    // Docs whose module no longer exists (split/merge/deleted dirs).
    if (deletedModuleIds.length > 0) {

        await prisma.moduleDoc.deleteMany({
            where: { repo_id: repoId, module_id: { in: deletedModuleIds } },
        });
    }

    // ---- L6b: cross-doc validation -> apply patches -----------------------------
    const validationPrompt = buildValidationPrompt(moduleDocs, modules, edges);

    const { data: validation } = await generate<{ findings: ValidationFinding[] }>(
        "validation", validationPrompt, VALIDATION_SCHEMA,
    );

    const { updatedDocs, appliedPatches, flaggedFindings } =
        applyValidationFindings(moduleDocs, validation.findings);

    // Patched docs must be re-persisted (the per-call upsert stored pre-patch).
    if (appliedPatches.length > 0) {

        const patchedIds = new Set(appliedPatches.map(p => p.moduleId));

        for (const moduleId of patchedIds) {

            await prisma.moduleDoc.update({
                where: { repo_id_module_id: { repo_id: repoId, module_id: moduleId } },
                data: { markdown: updatedDocs.get(moduleId)! },
            });
        }
    }

    // ---- L6c: architecture doc over the CORRECTED docs ---------------------------
    const archPrompt = buildArchPrompt(
        updatedDocs,
        edges,
        guessEntryPoints(codeFiles),
        intent,
        buildFileTree([...codeFiles, ...others]),
        custom.arch,
    );

    // Structured output: { markdown, commitMessage, prTitle, prBody } — the
    // PR metadata rides as separate fields, never inside the markdown.
    const { data: arch } = await generate<ArchDocResult>("archDoc", archPrompt, ARCH_DOC_SCHEMA);
    const archDoc = arch.markdown;

    // ---- Output 2: owner report ----------------------------------------------------
    const ownerReport = buildOwnerReport(incompleteByModule, flaggedFindings);

    // ---- Persist run-level state ------------------------------------------------------
    await prisma.repoDocState.upsert({
        where: { repo_id: repoId },
        create: {
            repo_id: repoId,
            arch_doc: archDoc,
            owner_report: ownerReport,
            intent_hash: intent.intentHash,
            prompt_version: effectiveVersion,
            resolution_rate: resolutionRate,
            route_kind: "NORMAL",
        },
        update: {
            arch_doc: archDoc,
            owner_report: ownerReport,
            intent_hash: intent.intentHash,
            prompt_version: effectiveVersion,
            resolution_rate: resolutionRate,
            route_kind: "NORMAL",
        },
    });

    // Key the worker-facing map by md FILENAME (from display names, unique),
    // so the caller can write files directly. The DB stays keyed by module_id —
    // that is the stable identity the staleness hashes diff against.
    const fileNames = buildDocFileNames(modules);

    const docsByFileName: Record<string, string> = {};
    const fileIndex: Record<string, string> = {};

    for (const [moduleId, markdown] of updatedDocs) {

        const fileName = fileNames.get(moduleId) ?? `${moduleId.replace(/[/\\]/g, "-")}.md`;
        docsByFileName[fileName] = markdown;
        fileIndex[fileName] = moduleId;
    }

    await persistDocsPointer(repoId, git, warnings);

    return {
        route: "NORMAL",
        moduleDocCount: updatedDocs.size,
        moduleDocs: docsByFileName,
        fileIndex,
        archDoc,
        archDocFileName: "ARCHITECTURE.md",
        ownerReport,
        warnings,
        commitMessage: arch.commitMessage,
        prTitle: arch.prTitle,
        prBody: arch.prBody,
        stats: {
            modulesTotal: modules.length,
            modulesRegenerated: staleModules.length,
            modulesFromCache: cachedModuleIds.length,
            modulesDeleted: deletedModuleIds.length,
            resolutionRate,
            promptVersion: effectiveVersion,
        },
    };
};

// ============================================================================
// TINY route: whole repo -> one call -> one combined doc stored as arch_doc.
// ============================================================================

const runTinyPath = async (
    repoId: string,
    codeFiles: FileRecord[],
    others: FileRecord[],
    intent: IntentBundle,
    readFile: (path: string) => string,
    custom: CustomInstructions,
    effectiveVersion: string,
    warnings: string[],
): Promise<DocGenResult> => {

    // The tiny route emits one combined doc that is stored as arch_doc, so the
    // arch instructions are the ones that apply here.
    const prompt = buildTinyPrompt(codeFiles, others, intent, readFile, custom.arch);

    const { data } = await generate<TinyDocResult>("tinyDoc", prompt, TINY_DOC_SCHEMA);

    const ownerReport = buildOwnerReport(
        new Map([["(repo)", data.incomplete]]), [],
    );

    await prisma.repoDocState.upsert({
        where: { repo_id: repoId },
        create: {
            repo_id: repoId,
            arch_doc: data.markdown,
            owner_report: ownerReport,
            intent_hash: intent.intentHash,
            prompt_version: effectiveVersion,
            resolution_rate: null,
            route_kind: "TINY",
        },
        update: {
            arch_doc: data.markdown,
            owner_report: ownerReport,
            intent_hash: intent.intentHash,
            prompt_version: effectiveVersion,
            resolution_rate: null,
            route_kind: "TINY",
        },
    });

    return {
        route: "TINY",
        moduleDocCount: 0,
        moduleDocs: {},
        fileIndex: {},
        archDoc: data.markdown,
        archDocFileName: "ARCHITECTURE.md",
        ownerReport,
        warnings,
        commitMessage: data.commitMessage,
        prTitle: data.prTitle,
        prBody: data.prBody,
        stats: {
            modulesTotal: 0,
            modulesRegenerated: 0,
            modulesFromCache: 0,
            modulesDeleted: 0,
            resolutionRate: null,
            promptVersion: effectiveVersion,
        },
    };
};

// ============================================================================
// Webhook path — next build step. The engine above is already re-runnable
// (staleness is hash-driven), so this will be: checkout new SHA -> run the
// same flow -> only changed modules regenerate.
// ============================================================================

// ============================================================================
// The docs pointer: Repo.last_processed_commit = the SHA these docs describe.
// The engine is the ONLY writer — pointer and docs can never disagree. The
// webhook pipeline (pipeline.webhook.ts) reads it to pin the local clone and
// compute cumulative diffs.
// ============================================================================

const persistDocsPointer = async (
    githubRepoId: string,
    git: SimpleGit,
    warnings: string[],
): Promise<void> => {

    try {
        const sha = (await git.revparse(["HEAD"])).trim();

        await prisma.repo.update({
            where: { github_repo_id: githubRepoId },
            data: { last_processed_commit: sha },
        });
    } catch {
        warnings.push("failed to persist the docs pointer (last_processed_commit)");
    }
};
