import fs from "node:fs";
import nodePath from "node:path";
import simpleGit, { SimpleGit } from "simple-git";

import prisma from "../prisma/prisma";
import { generate, llmConcurrency } from "../LLM/index";
import { scopedLogger, startTimer } from "../utils/logger.utils";
import { markStage } from "./pipeline.progress";

import {
    FileRecord, IntentBundle, Module, ModuleDocResult, ValidationFinding, IncompleteFeature,
    TinyDocResult, ArchDocResult, CustomInstructions,
} from "./pipeline.types";
import {
    mapWithConcurrency, buildFileTree, guessEntryPoints, buildDocFileNames,
} from "./pipeline.helper";
import { loadCustomInstructions } from "./pipeline.customInstructions";

import { getRepoFiles } from "./stages/L1.inventory";
import { groupModules, buildFileToModuleIndex } from "./stages/L2.prefixCompressor";
import { buildModuleEdges } from "./stages/L3.dynamicGrouper";
import { buildIntentBundle } from "./stages/L4.intentBundle";
import { isTinyRepo, computeStaleness } from "./stages/L5.router";
import {
    buildModulePrompt, buildArchPrompt, buildValidationPrompt, buildTinyPrompt,
    buildOwnerReport,
} from "./stages/L6.promptBuilder";
import { MODULE_DOC_SCHEMA, VALIDATION_SCHEMA, TINY_DOC_SCHEMA, ARCH_DOC_SCHEMA } from "./stages/L6.prompts";
import { applyValidationFindings } from "./stages/L6.applyEdits";

// ============================================================================
// The worker-facing result: how many md files were produced, plus the content.
// ============================================================================

export interface DocGenResult {
    route: "TINY" | "NORMAL";
    moduleDocCount: number;
    moduleDocs: Record<string, string>;    // "auth.md" -> markdown (ready to write to disk)
    fileIndex: Record<string, string>;     // "auth.md" -> module id (trace back to DB rows)
    archDoc: string;                       // always exactly one arch doc
    archDocFileName: string;               // "ARCHITECTURE.md"
    ownerReport: string | null;            // second output: message to the repo owner

    // Non-fatal problems worth telling the user about. The worker copies these
    // into the run's notification row.
    warnings: string[];

    // PR metadata for committing the docs — generated by the final LLM call
    // (arch call on NORMAL, tiny call on TINY) as SEPARATE structured fields,
    // so none of it can appear inside the doc markdown above.
    commitMessage: string;
    prTitle: string;
    prBody: string;
    stats: {
        modulesTotal: number;
        modulesRegenerated: number;
        modulesFromCache: number;
        modulesDeleted: number;
        resolutionRate: number | null;
        promptVersion: string;
    };
}

// ============================================================================
// generateFirstTimeDocs — the full first-import pipeline, L1 -> L6.
//
// This is ALSO safe to re-run at any time: staleness is computed against
// module_docs rows, so an interrupted import resumes where it stopped, and a
// second invocation on an unchanged repo skips every module call (see L5).
// ============================================================================

export const generateFirstTimeDocs = async (
    repoId: string,
    repoPath: string,
): Promise<DocGenResult> => {

    const log = scopedLogger("engine", { repo: repoId });
    const runElapsed = startTimer();

    log.info({ repoPath }, "engine start");

    const warnings: string[] = [];

    // ---- L0: the owner's custom instructions -------------------------------
    // effectiveVersion folds the instructions into the staleness key, so editing
    // them regenerates the docs they influenced.
    await markStage(repoId, "CUSTOM_INSTRUCTIONS");

    const { custom, effectiveVersion } = await loadCustomInstructions(repoId, warnings);

    log.info(
        {
            archPrompt: Boolean(custom.arch),
            modulePrompt: Boolean(custom.module),
            effectiveVersion,
        },
        "L0 custom instructions loaded",
    );

    // ---- L0/L1: inventory --------------------------------------------------
    await markStage(repoId, "INVENTORY");

    const git = simpleGit(repoPath);
    const inventoryElapsed = startTimer();

    const { codeFiles, intentFiles, others } = await getRepoFiles(git, repoPath);

    log.info(
        {
            codeFiles: codeFiles.length,
            intentFiles: intentFiles.length,
            others: others.length,
            ms: inventoryElapsed(),
        },
        `L1 inventory: ${codeFiles.length} code files, ${intentFiles.length} intent files, ${others.length} other`,
    );

    // Cached reader: L3 reads every code file, L6 reads many again — one disk
    // hit per file. Repo-relative path in, source text out.
    const cache = new Map<string, string>();

    const readFile = (relPath: string): string => {

        if (!cache.has(relPath)) {
            cache.set(relPath, fs.readFileSync(nodePath.join(repoPath, relPath), "utf8"));
        }

        return cache.get(relPath)!;
    };

    // ---- L4: intent bundle (needed on BOTH routes) ---------------------------
    await markStage(repoId, "INTENT_BUNDLE");

    const intent = buildIntentBundle(intentFiles, readFile);

    log.info({ intentHash: intent.intentHash }, "L4 intent bundle built");

    // ---- L5a: size decision — before any grouping/graph work ------------------
    await markStage(repoId, "ROUTING");

    if (isTinyRepo([...codeFiles, ...others])) {

        log.info("L5a route=TINY — whole repo fits in one call, skipping L2/L3");

        const tinyResult = await runTinyPath(repoId, codeFiles, others, intent, readFile, custom, effectiveVersion, warnings);
        await persistDocsPointer(repoId, git, warnings);

        log.info({ ms: runElapsed() }, "engine done (TINY)");

        return tinyResult;
    }

    log.info("L5a route=NORMAL — grouping into modules");

    // ---- L2/L3: deterministic layer -------------------------------------------
    await markStage(repoId, "GROUPING");

    const modules: Module[] = groupModules(codeFiles, others, { promptVersion: effectiveVersion });
    const fileToModule = buildFileToModuleIndex(modules);

    log.info({ modules: modules.length }, `L2 grouped into ${modules.length} modules`);
    log.debug({ moduleIds: modules.map(m => m.id) }, "L2 module ids");

    await markStage(repoId, "IMPORT_GRAPH");

    const { edges, resolutionRate, fileImportCounts } =
        buildModuleEdges(codeFiles, readFile, fileToModule);

    log.info(
        { edges: edges.length, resolutionRate },
        `L3 import graph: ${edges.length} edges, ${Math.round((resolutionRate ?? 0) * 100)}% of imports resolved`,
    );

    // ---- L5b: staleness — empty table on a true first run => all stale --------
    await markStage(repoId, "STALENESS");

    const storedRows = await prisma.moduleDoc.findMany({
        where: { repo_id: repoId },
        select: { module_id: true, input_hash: true },
    });

    const storedHashes = new Map(storedRows.map(r => [r.module_id, r.input_hash]));

    const { staleModules, cachedModuleIds, deletedModuleIds } =
        computeStaleness(modules, storedHashes);

    log.info(
        {
            stale: staleModules.length,
            cached: cachedModuleIds.length,
            deleted: deletedModuleIds.length,
        },
        `L5b staleness: ${staleModules.length} to regenerate, ${cachedModuleIds.length} from cache, ${deletedModuleIds.length} to delete`,
    );

    // ---- L6a: module docs (fan-out, cache-warm-first, per-call persist) -------
    const moduleDocs = new Map<string, string>();
    const incompleteByModule = new Map<string, IncompleteFeature[]>();

    // Progress is reported per COMPLETED module rather than per started one, so
    // the counter the frontend polls never runs ahead of the docs on disk.
    let modulesDone = 0;

    const generateOne = async (module: Module): Promise<void> => {

        const moduleElapsed = startTimer();

        log.debug({ module: module.id, files: module.files.length }, `module doc start: ${module.id}`);

        const prompt = buildModulePrompt(module, readFile, edges, intent, fileImportCounts, custom.module);

        const { data } = await generate<ModuleDocResult>("moduleDoc", prompt, MODULE_DOC_SCHEMA);

        moduleDocs.set(module.id, data.markdown);
        incompleteByModule.set(module.id, data.incomplete);

        // Persist IMMEDIATELY, not at the end of the run: if the process dies
        // at module 31/40, the next invocation finds 31 matching hashes and
        // only pays for the remaining 9. This upsert IS the crash-resume.
        await prisma.moduleDoc.upsert({
            where: { repo_id_module_id: { repo_id: repoId, module_id: module.id } },
            create: {
                repo_id: repoId,
                module_id: module.id,
                display_name: module.displayName,
                input_hash: module.inputHash,
                markdown: data.markdown,
                incomplete: JSON.parse(JSON.stringify(data.incomplete)),
            },
            update: {
                display_name: module.displayName,
                input_hash: module.inputHash,
                markdown: data.markdown,
                incomplete: JSON.parse(JSON.stringify(data.incomplete)),
            },
        });

        modulesDone++;

        log.info(
            { module: module.id, incomplete: data.incomplete.length, ms: moduleElapsed() },
            `module doc ${modulesDone}/${staleModules.length}: ${module.id}`,
        );

        await markStage(repoId, "MODULE_DOCS", {
            detail: `Writing module documentation — ${module.displayName}`,
            done: modulesDone,
            total: staleModules.length,
        });
    };

    if (staleModules.length > 0) {

        await markStage(repoId, "MODULE_DOCS", {
            detail: `Writing documentation for ${staleModules.length} module${staleModules.length === 1 ? "" : "s"}`,
            done: 0,
            total: staleModules.length,
        });

        const fanOutElapsed = startTimer();

        // First call alone: it WRITES the shared prompt-prefix cache;
        // the concurrent rest then READ it at ~10% input price.
        await generateOne(staleModules[0]);

        await mapWithConcurrency(staleModules.slice(1), llmConcurrency(), generateOne);

        log.info(
            { modules: staleModules.length, concurrency: llmConcurrency(), ms: fanOutElapsed() },
            `L6a all ${staleModules.length} module docs written`,
        );
    }
    else {
        log.info("L6a no stale modules — every module doc served from cache");
    }

    // Cached modules (crash-resume / re-run): load stored docs so validation
    // and the arch call always see the COMPLETE doc set.
    if (cachedModuleIds.length > 0) {

        const cachedRows = await prisma.moduleDoc.findMany({
            where: { repo_id: repoId, module_id: { in: cachedModuleIds } },
        });

        for (const row of cachedRows) {
            moduleDocs.set(row.module_id, row.markdown);
            incompleteByModule.set(row.module_id, row.incomplete as unknown as IncompleteFeature[]);
        }

        log.info({ loaded: cachedRows.length }, `loaded ${cachedRows.length} cached module docs`);
    }

    // Docs whose module no longer exists (split/merge/deleted dirs).
    if (deletedModuleIds.length > 0) {

        await markStage(repoId, "PRUNING", {
            detail: `Removing ${deletedModuleIds.length} doc${deletedModuleIds.length === 1 ? "" : "s"} for modules that no longer exist`,
        });

        await prisma.moduleDoc.deleteMany({
            where: { repo_id: repoId, module_id: { in: deletedModuleIds } },
        });

        log.info({ deleted: deletedModuleIds }, `pruned ${deletedModuleIds.length} orphaned module docs`);
    }

    // ---- L6b: cross-doc validation -> apply patches -----------------------------
    await markStage(repoId, "VALIDATION");

    const validationElapsed = startTimer();
    const validationPrompt = buildValidationPrompt(moduleDocs, modules, edges);

    const { data: validation } = await generate<{ findings: ValidationFinding[] }>(
        "validation", validationPrompt, VALIDATION_SCHEMA,
    );

    const { updatedDocs, appliedPatches, flaggedFindings } =
        applyValidationFindings(moduleDocs, validation.findings);

    log.info(
        {
            findings: validation.findings.length,
            applied: appliedPatches.length,
            flagged: flaggedFindings.length,
            ms: validationElapsed(),
        },
        `L6b validation: ${validation.findings.length} findings, ${appliedPatches.length} patches applied, ${flaggedFindings.length} flagged for the owner`,
    );

    // Patched docs must be re-persisted (the per-call upsert stored pre-patch).
    if (appliedPatches.length > 0) {

        const patchedIds = new Set(appliedPatches.map(p => p.moduleId));

        for (const moduleId of patchedIds) {

            await prisma.moduleDoc.update({
                where: { repo_id_module_id: { repo_id: repoId, module_id: moduleId } },
                data: { markdown: updatedDocs.get(moduleId)! },
            });
        }

        log.info({ patchedModules: [...patchedIds] }, `re-persisted ${patchedIds.size} patched module docs`);
    }

    // ---- L6c: architecture doc over the CORRECTED docs ---------------------------
    await markStage(repoId, "ARCH_DOC");

    const archElapsed = startTimer();

    const archPrompt = buildArchPrompt(
        updatedDocs,
        edges,
        guessEntryPoints(codeFiles),
        intent,
        buildFileTree([...codeFiles, ...others]),
        custom.arch,
    );

    // Structured output: { markdown, commitMessage, prTitle, prBody } — the
    // PR metadata rides as separate fields, never inside the markdown.
    const { data: arch } = await generate<ArchDocResult>("archDoc", archPrompt, ARCH_DOC_SCHEMA);
    const archDoc = arch.markdown;

    log.info({ chars: archDoc.length, ms: archElapsed() }, "L6c architecture doc written");

    // ---- Output 2: owner report ----------------------------------------------------
    const ownerReport = buildOwnerReport(incompleteByModule, flaggedFindings);

    log.info({ hasOwnerReport: Boolean(ownerReport) },
        ownerReport ? "owner report produced (unfinished work was excluded)" : "no owner report needed");

    // ---- Persist run-level state ------------------------------------------------------
    // Only the doc ARTIFACTS here — the run's stage/status columns on this same
    // row are owned by pipeline.progress and must not be clobbered.
    await markStage(repoId, "PERSISTING");

    await prisma.repoDocState.upsert({
        where: { repo_id: repoId },
        create: {
            repo_id: repoId,
            arch_doc: archDoc,
            owner_report: ownerReport,
            intent_hash: intent.intentHash,
            prompt_version: effectiveVersion,
            resolution_rate: resolutionRate,
            route_kind: "NORMAL",
        },
        update: {
            arch_doc: archDoc,
            owner_report: ownerReport,
            intent_hash: intent.intentHash,
            prompt_version: effectiveVersion,
            resolution_rate: resolutionRate,
            route_kind: "NORMAL",
        },
    });

    // Key the worker-facing map by md FILENAME (from display names, unique),
    // so the caller can write files directly. The DB stays keyed by module_id —
    // that is the stable identity the staleness hashes diff against.
    const fileNames = buildDocFileNames(modules);

    const docsByFileName: Record<string, string> = {};
    const fileIndex: Record<string, string> = {};

    for (const [moduleId, markdown] of updatedDocs) {

        const fileName = fileNames.get(moduleId) ?? `${moduleId.replace(/[/\\]/g, "-")}.md`;
        docsByFileName[fileName] = markdown;
        fileIndex[fileName] = moduleId;
    }

    await persistDocsPointer(repoId, git, warnings);

    log.info(
        {
            route: "NORMAL",
            moduleDocs: updatedDocs.size,
            regenerated: staleModules.length,
            fromCache: cachedModuleIds.length,
            warnings: warnings.length,
            ms: runElapsed(),
        },
        `engine done (NORMAL): ${updatedDocs.size} module docs + architecture doc in ${runElapsed()}ms`,
    );

    return {
        route: "NORMAL",
        moduleDocCount: updatedDocs.size,
        moduleDocs: docsByFileName,
        fileIndex,
        archDoc,
        archDocFileName: "ARCHITECTURE.md",
        ownerReport,
        warnings,
        commitMessage: arch.commitMessage,
        prTitle: arch.prTitle,
        prBody: arch.prBody,
        stats: {
            modulesTotal: modules.length,
            modulesRegenerated: staleModules.length,
            modulesFromCache: cachedModuleIds.length,
            modulesDeleted: deletedModuleIds.length,
            resolutionRate,
            promptVersion: effectiveVersion,
        },
    };
};

// ============================================================================
// TINY route: whole repo -> one call -> one combined doc stored as arch_doc.
// ============================================================================

const runTinyPath = async (
    repoId: string,
    codeFiles: FileRecord[],
    others: FileRecord[],
    intent: IntentBundle,
    readFile: (path: string) => string,
    custom: CustomInstructions,
    effectiveVersion: string,
    warnings: string[],
): Promise<DocGenResult> => {

    const log = scopedLogger("engine", { repo: repoId });
    const tinyElapsed = startTimer();

    // The tiny route emits one combined doc that is stored as arch_doc, so the
    // arch instructions are the ones that apply here.
    await markStage(repoId, "TINY_DOC", {
        detail: `Writing a combined document for ${codeFiles.length} source files`,
    });

    const prompt = buildTinyPrompt(codeFiles, others, intent, readFile, custom.arch);

    const { data } = await generate<TinyDocResult>("tinyDoc", prompt, TINY_DOC_SCHEMA);

    log.info(
        { chars: data.markdown.length, incomplete: data.incomplete.length, ms: tinyElapsed() },
        "TINY combined doc written",
    );

    const ownerReport = buildOwnerReport(
        new Map([["(repo)", data.incomplete]]), [],
    );

    await markStage(repoId, "PERSISTING");

    await prisma.repoDocState.upsert({
        where: { repo_id: repoId },
        create: {
            repo_id: repoId,
            arch_doc: data.markdown,
            owner_report: ownerReport,
            intent_hash: intent.intentHash,
            prompt_version: effectiveVersion,
            resolution_rate: null,
            route_kind: "TINY",
        },
        update: {
            arch_doc: data.markdown,
            owner_report: ownerReport,
            intent_hash: intent.intentHash,
            prompt_version: effectiveVersion,
            resolution_rate: null,
            route_kind: "TINY",
        },
    });

    return {
        route: "TINY",
        moduleDocCount: 0,
        moduleDocs: {},
        fileIndex: {},
        archDoc: data.markdown,
        archDocFileName: "ARCHITECTURE.md",
        ownerReport,
        warnings,
        commitMessage: data.commitMessage,
        prTitle: data.prTitle,
        prBody: data.prBody,
        stats: {
            modulesTotal: 0,
            modulesRegenerated: 0,
            modulesFromCache: 0,
            modulesDeleted: 0,
            resolutionRate: null,
            promptVersion: effectiveVersion,
        },
    };
};

// ============================================================================
// Webhook path — next build step. The engine above is already re-runnable
// (staleness is hash-driven), so this will be: checkout new SHA -> run the
// same flow -> only changed modules regenerate.
// ============================================================================

// ============================================================================
// The docs pointer: Repo.last_processed_commit = the SHA these docs describe.
// The engine is the ONLY writer — pointer and docs can never disagree. The
// webhook pipeline (pipeline.webhook.ts) reads it to pin the local clone and
// compute cumulative diffs.
// ============================================================================

const persistDocsPointer = async (
    githubRepoId: string,
    git: SimpleGit,
    warnings: string[],
): Promise<void> => {

    const log = scopedLogger("engine", { repo: githubRepoId });

    try {
        const sha = (await git.revparse(["HEAD"])).trim();

        await prisma.repo.update({
            where: { github_repo_id: githubRepoId },
            data: { last_processed_commit: sha },
        });

        log.info({ sha }, `docs pointer advanced to ${sha.slice(0, 8)}`);
    } catch (err) {
        log.error({ err }, "failed to persist the docs pointer (last_processed_commit)");
        warnings.push("failed to persist the docs pointer (last_processed_commit)");
    }
};
