import { LlmPrompt, LlmProvider, LlmUsage } from "../llm.types";
import { logger } from "../../utils/logger.utils";

// Stand-in for a real provider until there is an API subscription. Same
// signature as anthropic.provider, so switching is a one-line change in
// llm.config.ts — no caller ever changes.

const DUMMY_MARKDOWN = `## Purpose

Hey nice project.

## Public surface

Hey nice project.

## How it works

Hey nice project.

## Interactions

Hey nice project.

## Gotchas

Hey nice project.
`;

// Per-field canned text, so the fake output still flows through the PR/commit
// path sensibly. Anything not listed falls back to a generic line.
const TEXT_BY_FIELD: Record<string, string> = {
    markdown: DUMMY_MARKDOWN,
    commitMessage: "docs: add generated project documentation",
    prTitle: "Add generated project documentation",
    prBody: "Hey nice project.\n\nGenerated by the dummy LLM provider.",
    reason: "Hey nice project.",
};

const FALLBACK_TEXT = "Hey nice project.";

// A real response takes seconds; a little latency keeps the concurrency paths
// behaving like they will in production.
const LATENCY_MS = 25;

interface JsonSchemaNode {
    type?: string;
    enum?: readonly unknown[];
    properties?: Record<string, JsonSchemaNode>;
    required?: readonly string[];
    items?: JsonSchemaNode;
}

/**
 * Build the smallest value that satisfies a JSON-Schema node, so the dummy
 * works for every role's schema without knowing which role called it.
 * Arrays come back empty: no invented findings or incomplete features.
 */
function fillSchema(node: JsonSchemaNode, field = ""): unknown {

    switch (node.type) {

        case "object": {
            const properties = node.properties ?? {};
            const keys = node.required ?? Object.keys(properties);

            const result: Record<string, unknown> = {};

            for (const key of keys) {
                const child = properties[key];
                if (child) result[key] = fillSchema(child, key);
            }

            return result;
        }

        case "array":
            return [];

        case "boolean":
            // updateJudge reads this: true means "regenerate", the safe default.
            return true;

        case "number":
        case "integer":
            return 0;

        default:
            if (node.enum?.length) return node.enum[0];
            return TEXT_BY_FIELD[field] ?? FALLBACK_TEXT;
    }
}

const approxTokens = (chars: number): number => Math.ceil(chars / 4);

export const dummyProvider: LlmProvider = {

    async generate(
        model: string,
        maxTokens: number,
        prompt: LlmPrompt,
        schema?: Record<string, unknown>,
    ): Promise<{ text: string; usage: LlmUsage }> {

        await new Promise(resolve => setTimeout(resolve, LATENCY_MS));

        const node = schema as JsonSchemaNode | undefined;

        // index.ts JSON.parses the text whenever a schema was given, so a
        // schema call must get JSON back — the markdown rides in its field.
        const text = node
            ? JSON.stringify(fillSchema(node))
            : DUMMY_MARKDOWN;

        // Fabricated but proportional, so token/cost logging stays plausible.
        const cachedChars = prompt.system
            .filter(block => block.cache)
            .reduce((sum, block) => sum + block.text.length, 0);

        const freshChars = prompt.system
            .filter(block => !block.cache)
            .reduce((sum, block) => sum + block.text.length, 0) + prompt.user.length;

        logger.info(`[dummy-llm] model=${model} maxTokens=${maxTokens} structured=${Boolean(node)}`);

        return {
            text,
            usage: {
                inputTokens: approxTokens(freshChars),
                outputTokens: approxTokens(text.length),
                cacheReadTokens: 0,
                cacheWriteTokens: approxTokens(cachedChars),
            },
        };
    },
};
